name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - source: index.html
            destination: index.html
          - source: docs/simple-ruby/index.html
            destination: docs/simple-ruby/index.html
          # - source: gap-analysis/index.html
            # destination defaults to gap-analysis/index.html
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: respec
